name: netpulse
description: "Network analysis tool for network administrators."
publish_to: 'none'

version: 0.0.2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  dart_ping: ^9.0.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  connectivity_plus: 7.1.1
  wifi_iot: ^0.3.19+2
  routeros_api: ^0.1.4
  permission_handler: ^12.0.1
  http: ^1.6.0
  file_picker: 8.1.7
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  fl_chart: ^1.2.0
  xml: ^6.6.1
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "netpulse.png"
  min_sdk_android: 25
